---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Format
        run: nix develop --command treefmt --fail-on-change

  demo-firmware:
    name: Demo Firmware
    needs:
      - formatting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        demo:
          - rp2040
          - rp235xa

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Clippy
        run: |
          cd ./demo-firmware/${{ matrix.demo }}
          nix develop --command cargo clippy -- -Dwarnings

      - name: Clippy
        run: |
          cd ./demo-firmware/${{ matrix.demo }}
          nix develop --command cargo clippy -- -Dwarnings
